---
name: Django # Name of the workflow

on: [push] # Trigger the workflow on a push event to any branch in the repo

jobs:
    lint:
        name: Run linters
        runs-on: ubuntu-latest

        steps:
            - name: Check out Git repository
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.10.14

            - name: Install pre-commit
              run: pip install pre-commit

            - name: Run pre-commit on all files
              run: pre-commit run --all-files

    test: # Define a job named 'test'
        name: Run unit tests # A more descriptive name for the job
        runs-on: ubuntu-22.04 # Specify the runner environment (Ubuntu 22.04)
        needs: lint

        steps: # Steps to be run as part of this job
            - name: Login to Docker Hub # Step 1: Log in to Docker Hub
              uses: docker/login-action@v1 # Use the docker/login-action to log in to Docker Hub
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }} # Use the stored Docker Hub username
                  password: ${{ secrets.DOCKERHUB_TOKEN }} # Use the stored Docker Hub token for authentication

            - name: Checkout # Step 2: Checkout the repository code
              uses: actions/checkout@v2 # Use the checkout action to checkout the code

            - name: Test Places # Step 3: Run the tests for places
              run: docker-compose run web python manage.py test places.tests # Use Docker Compose to run the Django unit tests

            - name: Test Users # Step 4: Run the tests for users
              run: docker-compose run web python manage.py test users.tests # Use Docker Compose to run the Django unit tests
